[2025-07-22T11:33:24.851+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-22T11:33:24.876+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mlops_spotify_pipeline.preprocess_data manual__2025-07-22T11:28:16.422907+00:00 [queued]>
[2025-07-22T11:33:24.883+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mlops_spotify_pipeline.preprocess_data manual__2025-07-22T11:28:16.422907+00:00 [queued]>
[2025-07-22T11:33:24.883+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-07-22T11:33:24.895+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocess_data> on 2025-07-22 11:28:16.422907+00:00
[2025-07-22T11:33:24.903+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mlops_spotify_pipeline', 'preprocess_data', 'manual__2025-07-22T11:28:16.422907+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/spotify_crawl_dag.py', '--cfg-path', '/tmp/tmp_4f58lm8']
[2025-07-22T11:33:24.906+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask preprocess_data
[2025-07-22T11:33:24.907+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=400) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-22T11:33:24.907+0000] {standard_task_runner.py:63} INFO - Started process 413 to run task
[2025-07-22T11:33:24.958+0000] {task_command.py:426} INFO - Running <TaskInstance: mlops_spotify_pipeline.preprocess_data manual__2025-07-22T11:28:16.422907+00:00 [running]> on host d0316ef76a14
[2025-07-22T11:33:25.035+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mlops_spotify_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-22T11:28:16.422907+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-22T11:28:16.422907+00:00'
[2025-07-22T11:33:25.036+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-22T11:33:25.046+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-22T11:33:25.047+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/spotify_crawl_dag.py", line 34, in preprocess_data_wrapper
    if not os.path.exists(file_path):
           ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2025-07-22T11:33:25.060+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=mlops_spotify_pipeline, task_id=preprocess_data, run_id=manual__2025-07-22T11:28:16.422907+00:00, execution_date=20250722T112816, start_date=20250722T113324, end_date=20250722T113325
[2025-07-22T11:33:25.068+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 28 for task preprocess_data (name 'os' is not defined; 413)
[2025-07-22T11:33:25.081+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-22T11:33:25.099+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-22T11:33:25.103+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
