[2025-07-22T12:23:56.897+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: mlops_spotify_pipeline.preprocess_data manual__2025-07-22T12:18:51.006769+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
