[2025-07-22T12:41:24.206+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-22T12:41:24.234+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mlops_spotify_pipeline.crawl_data manual__2025-07-22T12:41:22.523095+00:00 [queued]>
[2025-07-22T12:41:24.240+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mlops_spotify_pipeline.crawl_data manual__2025-07-22T12:41:22.523095+00:00 [queued]>
[2025-07-22T12:41:24.241+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-22T12:41:24.252+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crawl_data> on 2025-07-22 12:41:22.523095+00:00
[2025-07-22T12:41:24.261+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mlops_spotify_pipeline', 'crawl_data', 'manual__2025-07-22T12:41:22.523095+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/spotify_crawl_dag.py', '--cfg-path', '/tmp/tmphhh62dym']
[2025-07-22T12:41:24.265+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask crawl_data
[2025-07-22T12:41:24.265+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=185) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-22T12:41:24.265+0000] {standard_task_runner.py:63} INFO - Started process 198 to run task
[2025-07-22T12:41:24.323+0000] {task_command.py:426} INFO - Running <TaskInstance: mlops_spotify_pipeline.crawl_data manual__2025-07-22T12:41:22.523095+00:00 [running]> on host c0ba1ce2cd81
[2025-07-22T12:41:24.419+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mlops_spotify_pipeline' AIRFLOW_CTX_TASK_ID='crawl_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-22T12:41:22.523095+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-22T12:41:22.523095+00:00'
[2025-07-22T12:41:24.420+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-22T12:41:24.452+0000] {checkpoint_manager.py:12} INFO - Loaded checkpoint with 6 playlist IDs
[2025-07-22T12:41:24.453+0000] {spotify_crawl_dag.py:18} INFO - Found 6 pending playlists
[2025-07-22T12:41:24.454+0000] {spotify_crawl_dag.py:22} INFO - Processing playlist 6XFOsAdp88ptBCdqUMAfmP
[2025-07-22T12:41:24.459+0000] {spotify_crawl_dag.py:29} ERROR - Unexpected error for playlist 6XFOsAdp88ptBCdqUMAfmP: 'client_id'
[2025-07-22T12:41:24.460+0000] {checkpoint_manager.py:19} INFO - Saving checkpoint with 6 playlist IDs
[2025-07-22T12:41:24.467+0000] {spotify_crawl_dag.py:22} INFO - Processing playlist 2JaUyOhoyfmDJlQy1CYjQm
[2025-07-22T12:41:24.470+0000] {spotify_crawl_dag.py:29} ERROR - Unexpected error for playlist 2JaUyOhoyfmDJlQy1CYjQm: 'client_id'
[2025-07-22T12:41:24.471+0000] {checkpoint_manager.py:19} INFO - Saving checkpoint with 6 playlist IDs
[2025-07-22T12:41:24.473+0000] {spotify_crawl_dag.py:22} INFO - Processing playlist 02zSPmcae3ct4moT8om7kK
[2025-07-22T12:41:24.476+0000] {spotify_crawl_dag.py:29} ERROR - Unexpected error for playlist 02zSPmcae3ct4moT8om7kK: 'client_id'
[2025-07-22T12:41:24.478+0000] {checkpoint_manager.py:19} INFO - Saving checkpoint with 6 playlist IDs
[2025-07-22T12:41:24.480+0000] {spotify_crawl_dag.py:22} INFO - Processing playlist 1SkrX3lyW8UBELc68IRC4j
[2025-07-22T12:41:24.483+0000] {spotify_crawl_dag.py:29} ERROR - Unexpected error for playlist 1SkrX3lyW8UBELc68IRC4j: 'client_id'
[2025-07-22T12:41:24.484+0000] {checkpoint_manager.py:19} INFO - Saving checkpoint with 6 playlist IDs
[2025-07-22T12:41:24.487+0000] {spotify_crawl_dag.py:22} INFO - Processing playlist 6VCsmVYfvQI8lmSMEAwWso
[2025-07-22T12:41:24.489+0000] {spotify_crawl_dag.py:29} ERROR - Unexpected error for playlist 6VCsmVYfvQI8lmSMEAwWso: 'client_id'
[2025-07-22T12:41:24.491+0000] {checkpoint_manager.py:19} INFO - Saving checkpoint with 6 playlist IDs
[2025-07-22T12:41:24.493+0000] {spotify_crawl_dag.py:22} INFO - Processing playlist 0mrqaVOe6KYEEcaSYhVK4a
[2025-07-22T12:41:24.496+0000] {spotify_crawl_dag.py:29} ERROR - Unexpected error for playlist 0mrqaVOe6KYEEcaSYhVK4a: 'client_id'
[2025-07-22T12:41:24.496+0000] {checkpoint_manager.py:19} INFO - Saving checkpoint with 6 playlist IDs
[2025-07-22T12:41:24.500+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-22T12:41:24.500+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-22T12:41:24.513+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mlops_spotify_pipeline, task_id=crawl_data, run_id=manual__2025-07-22T12:41:22.523095+00:00, execution_date=20250722T124122, start_date=20250722T124124, end_date=20250722T124124
[2025-07-22T12:41:24.560+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-22T12:41:24.587+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-22T12:41:24.590+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
