[2025-07-22T11:16:45.192+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-22T11:16:45.218+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mlops_spotify_pipeline.preprocess_data manual__2025-07-22T11:16:41.078857+00:00 [queued]>
[2025-07-22T11:16:45.224+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mlops_spotify_pipeline.preprocess_data manual__2025-07-22T11:16:41.078857+00:00 [queued]>
[2025-07-22T11:16:45.225+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-22T11:16:45.236+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocess_data> on 2025-07-22 11:16:41.078857+00:00
[2025-07-22T11:16:45.245+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mlops_spotify_pipeline', 'preprocess_data', 'manual__2025-07-22T11:16:41.078857+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/spotify_crawl_dag.py', '--cfg-path', '/tmp/tmpy51e3raa']
[2025-07-22T11:16:45.247+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask preprocess_data
[2025-07-22T11:16:45.248+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=216) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-22T11:16:45.249+0000] {standard_task_runner.py:63} INFO - Started process 229 to run task
[2025-07-22T11:16:45.297+0000] {task_command.py:426} INFO - Running <TaskInstance: mlops_spotify_pipeline.preprocess_data manual__2025-07-22T11:16:41.078857+00:00 [running]> on host 593ac97bdb94
[2025-07-22T11:16:45.370+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mlops_spotify_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-22T11:16:41.078857+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-22T11:16:41.078857+00:00'
[2025-07-22T11:16:45.371+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-22T11:16:45.383+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-22T11:16:45.383+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/spotify_crawl_dag.py", line 30, in preprocess_data_wrapper
    raise FileNotFoundError(f"File {file_path} not found.")
FileNotFoundError: File /opt/***/data/crawled_tracks.csv not found.
[2025-07-22T11:16:45.398+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_spotify_pipeline, task_id=preprocess_data, run_id=manual__2025-07-22T11:16:41.078857+00:00, execution_date=20250722T111641, start_date=20250722T111645, end_date=20250722T111645
[2025-07-22T11:16:45.407+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task preprocess_data (File /opt/***/data/crawled_tracks.csv not found.; 229)
[2025-07-22T11:16:45.422+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-22T11:16:45.443+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-22T11:16:45.445+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
